export const FETCHING_CHARACTERS = "FETCHING_CHARACTERS";
export const CHARACTERS_FETCH_SUCCESSFUL = "CHARACTERS_FETCH_SUCCESSFUL";
export const ERROR_FETCHING_CHARACTERS = "ERROR_FETCHING_CHARACTERS";

export const FETCHING_CHARACTER_ID = "FETCHING_CHARACTER_ID";
export const CHARACTER_ID_FETCH_SUCCESSFUL = "CHARACTER_ID_FETCH_SUCCESSFUL";