export const FETCHING_EPISODES = "FETCHING_EPISODES";
export const EPISODES_FETCH_SUCCESSFUL = "EPISODES_FETCH_SUCCESSFUL";
export const ERROR_FETCHING_EPISODES = "ERROR_FETCHING_EPISODES";

export const FETCHING_EPISODE_ID = "FETCHING_EPISODE_ID";
export const EPISODE_ID_FETCH_SUCCESSFUL = "EPISODE_ID_FETCH_SUCCESSFUL";