export const FETCHING_LOCATIONS = "FETCHING_LOCATIONS";
export const LOCATIONS_FETCH_SUCCESSFUL = "LOCATIONS_FETCH_SUCCESSFUL";
export const ERROR_FETCHING_LOCATIONS = "ERROR_FETCHING_LOCATIONS";

export const FETCHING_LOCATION_ID = "FETCHING_LOCATION_ID";
export const LOCATION_ID_FETCH_SUCCESSFUL = "LOCATION_ID_FETCH_SUCCESSFUL";